# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

<color=#EBBC4E>ZeenGoone Server</color>:
  address: beeheim.buzz
  port: 2401
  password: giffel
